config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "pages#home"

  get "/dashboard/random_friend", to: "friendships#create_random_friendship"
  get "/dashboard", to: "pages#dashboard"

  resources :sessions, only: [:create]
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"

  scope "/:uuid" do
    resources :messages, only: [:index, :show, :create, :new]
  end

  resources :users, only: [:new, :create]

  resources :friendships, only: [:create, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord

  belongs_to :user
  belongs_to :friend, class_name: "User"

  validate :uniquess_of_friendship

  private

  def uniquess_of_friendship
    user.friends.where(id: friend.id).pluck(:name)
    if user && friend && user.friends.where(id: friend.id).any?
      errors.add(:base, "Les utilisateurs sont déjà amis.")
    end
  end

end

app/models/message.rb
class Message < ApplicationRecord
  TIME_TO_WAIT = 2.hours
  validates :content, presence: true, length: { minimum: 280 }
  belongs_to :user
  belongs_to :recipient, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  validates :firstname, presence: true, length: { maximum: 50 }
  validates :lastname, presence: true, length: { maximum: 50 }
  validates :email, format: { with: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }, uniqueness: { case_sensitive: false }

  has_many :messages

  has_many :friendships, dependent: :destroy
  has_many :inverse_of_friendships, foreign_key: "friend_id", class_name: "Friendship", dependent: :destroy

  before_save :create_remember_token
  before_create :create_uuid

  def friends
    unless @friends
      invited = User.joins(:friendships).where("friendships.friend_id = ? AND friendships.accepted = ?", id, true).pluck(:id)
      received = User.joins(:inverse_of_friendships).where("friendships.user_id = ? AND friendships.accepted = ?", id, true).pluck(:id)
      @friends = User.where("id IN (?)", invited + received - [self.id])
    end
    @friends
  end

  # friend request sent but not acknowledged yet
  def pending_requests
    @pending_requests ||= self.friendships.where(pending: true)
  end

  # incoming request to be friend to be acknowledged
  def incoming_requests
    @incoming_requests ||= self.inverse_of_friendships.where(pending: true)
  end

  def full_name
    "#{firstname} #{lastname}"
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

  def create_uuid
    self.uuid = SecureRandom.hex(10)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  add_flash_types :success, :error

  protect_from_forgery

  def redirect_if_connected
    redirect_to root_path, error: "Vous êtes déjà connecté !" if signed_in?
  end

  def redirect_if_not_connected
    redirect_to root_path, success: "Veuillez vous connecter." unless signed_in?
  end


end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :redirect_if_not_connected

  # create a friend request
  def create
    @friend = User.find_by(uuid: params[:uuid])
    @friendship = Friendship.new(user: current_user, friend: @friend, pending: true)
    if @friendship.save
      redirect_to root_path, success: "Votre demande a été envoyée !"
    else
      redirect_to root_path, error: "Il y a eu un problème avec votre demande."
    end
  end

  def create_random_friendship
    tab_id = User.ids # I hope it works
    rd = rand(tab_id.length)
    @friend = User.find_by(id: rd)
    @friendship = Friendship.new(user: current_user, friend: @friend, pending: true)
    if @friendship.save
      redirect_to dashboard_path, success: "Votre demande a été envoyée !"
    else
      redirect_to dashboard_path, error: "Il y a eu un problème avec votre demande."
    end
  end

  # accept a friend request
  def update
    @friendship = current_user.incoming_requests.find(params[:id])
    @friendship.update(pending: false, accepted: true)
    redirect_to root_path, success: "Vous pouvez maintenant écrire à #{@friendship.friend.full_name}"
  end

  # refuse a friend request
  def destroy
    @friendship = current_user.incoming_requests.find(params[:id])
    @friendship.update(pending: false, accepted: false)
    redirect_to root_path, success: "Vous avez refusé l'invitation de #{@friendship.friend.full_name}"
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :redirect_if_not_connected, :fetch_recipient
  layout "mailbox"

  def new     # Get request
    @message = Message.new
    @message.user = current_user()
    @message.recipient = @recipient
  end
  
  def show    # Get request
    # Display a specific message to the current user
    @message = Message.find(params[:id])
    if @message.created_at + Message::TIME_TO_WAIT < Time.now
      redirect_to messages_path(uuid: @recipient.uuid), error: "Vous devez attendre que le message arrive"
    end
  end 
  
  def create  # post request
    @message = Message.new(message_params)
    @message.user = current_user()
    @message.recipient = @recipient # @recipient defined with before_action as member variable 
    if @message.save
      redirect_to messages_path(uuid: @recipient.uuid), success: "Votre message a bien été envoyé"
    else
      render 'new'
    end
  end

  def index   # get request
    # Display all Messages (sent & received) from specific friend 
    @sent_messages  = current_user.messages.where(recipient: @recipient)
    @received_messages = @recipient.messages.where(recipient: current_user)
  end

  private
  def message_params()
    params.require(:message).permit(
      :content
    )
  end

  def fetch_recipient()
    @recipient = current_user.friends.find_by(uuid: params[:uuid])
    if  !@recipient 
      redirect_to root_path, error: "Votre destinataire n'existe pas"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :redirect_if_not_connected, only: :dashboard

  def home
    @user = User.new
  end

  def dashboard
    render layout: "mailbox"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_connected, only: [:new, :create]
  before_action :redirect_if_not_connected, only: [:destroy]

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].strip.downcase)
    if @user && @user.authenticate(params[:session][:password])
      sign_in @user, permanent: params[:session][:remember_me] == "1"
      redirect_to root_path, success: "Vous êtes connecté !"
    else
      flash.now[:error] = "Nom d'utilisateur et/ou mot de passe incorrect(s)"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path, success: "Vous êtes déconnecté !"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
		if @user.save
			redirect_to root_path, success: "Un email de confirmation vous a été envoyé"
		else
			render 'new'
		end
  end

  private

  def user_params
    params.require(:user).permit(
      :firstname, :lastname, :email, :password, :password_confirmation
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Sign in a user with a cookie
  # 
  # * *Args*    :
  #   - a user to sign in
  # * *Returns* :
  #
  def sign_in(user, permanent: false)
    cookies[:remember_token] = { value: user.remember_token, expires: (Time.now + 2592000 if permanent) }
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  # Provid the user currently signed in.
  # 
  # * *Returns* :
  #   - the user currently signed in
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end


  # Check if there is a user signed in.
  # 
  # * *Returns* :
  #   - boolean
  def signed_in?
    !current_user.nil?
  end

  # Sign out a user by removing the cookie.
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

end

app/views/layouts/_flash.html.erb
<% if flash.any? %>

  <div id="flash">
  <% flash.each do |key, value| %>
      <p><%= value %></p>
  <% end %>
  </div>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dear Uknown</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>    
  </head>

  <body>

    <%= render "layouts/flash" %>

    <%= yield %>
    
  </body>
</html>

app/views/layouts/mailbox.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mailbox</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'mailbox', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

    <%= render "layouts/flash" %>

    <div id="header">
      <div class="menu_element">
        <%= link_to logout_path, method: :delete do %>
          <p>Log out</p>
        <% end %>
      </div>
      <div class="menu_element">
        <a id="profile" href="index.html">
          <p>Profile</p>
        </a>
      </div>
      <div id="close">
        <p onclick="closef(); "><b>X</b></p>
      </div>
    </div>

    <div id="left_part">
      <div id="correspondant">
        <button class="tablinks">
          <a href="/dashboard"><%= image_tag "box_close.png", id: "boxLetter" %></a>
        </button>
        <% current_user.friends.each do |friend| %>
          <a href="<%= messages_path(uuid: friend.uuid) %>"><button class="tablinks"><%= friend.full_name %></button></a>
        <% end %>
      </div>

      <div id="background" class="correspondance">
        <%= image_tag "logo_back.png", id: "back" %>
      </div>
    </div>

    <div id="center">
      <%= yield %>
    </div>

    <div id="right_section">

      <div id="stamp_box">
        <div id="stamp_img">
          <%= image_tag "stamp.png", id: "stamp" %>
        </div>
        <div id="stamp_number">
          <p><b>67</b></p>
        </div>
      </div>
      <div class="buttons" id="buy_button">
        <a href="index.html">
          <p>Donate</p>
        </a>
      </div>

    </div>

  </body>
</html>

app/views/messages/index.html.erb
<div id="buttons_zone">
  <div id="received_button" onclick="received_letters(); ">
    <p>RECU</p>
  </div>
  <div id="sent_button" onclick="sent_letters(); ">
    <p>ENVOYÉ</p>
  </div>
  <div id="nouveau" >
    <%= link_to new_message_path(uuid: params[:uuid]) do %>
    <p>NOUVEAU</p>
    <% end %>
  </div>
</div>
<div id="read_written">

  <% @received_messages.each do |sent_message| %>
    <div class="page_with_content">
      <div class="correspondance">
        <p><%= sent_message.content %></p>
      </div>
    </div>
  <% end %>

  <!--<div class="page_with_content">
    <div id="London" class="correspondance">
      <h3>London</h3>
      <p>London is the capital city of England.</p>
    </div>
  </div>-->

</div>

<div id="write_section">
  <% @sent_messages.each do |sent_message| %>
    <div class="page_with_content">
      <div class="correspondance">
        <p><%= sent_message.content %></p>
      </div>
    </div>
  <% end %>
</div>

<script>
  function received_letters() {
    document.getElementById("received_letter").style.visibility = "visible";
  }

  function sent_letters() {
    document.getElementById("sent_letter").style.visibility = "visible";
  }

  function writeNewLetter() {
    remove_correspondant();
    document.getElementById("write_section").style.visibility = "visible";
    document.getElementById("page_full").style.visibility = "visible";
    document.getElementById("close").style.visibility = "visible";
  }

  function closef() {
    document.getElementById("write_section").style.visibility = "hidden";
    document.getElementById("page_full").style.visibility = "hidden";
    document.getElementById("close").style.visibility = "hidden";
    remove_correspondant();
  }
</script>

app/views/messages/new.html.erb
<div id="page_full">
  <%= form_for @message, url: messages_path(uuid: params[:uuid]) do |f| %>

  <div id="page">
    <div id="page_inner_wrapper"></div>
    <p id="dear">To: <%= @message.recipient.full_name %></p>
    <div id="page_content">
      <%= f.text_area :content, id: "letter_content" %>
    </div>
  </div>
  <input type="submit" value="Send letter to the post office" class="submit_letter">

  <% end %>
</div>

app/views/messages/show.html.erb
<% @message.content %>

app/views/pages/dashboard.html.erb
<div id="new_corres">
  <div id="new_corres_wrapper">
    <input type="submit" value="Correspondant aléatoire" class="submit_letter" id="random">
    <%= form_with url: dashboard_random_friend_path, local: true, id: "get_user" do %>

      <%= text_field_tag :uuid, nil, { placeholder: "Code", id: "fill_user" } %>
      <%= submit_tag "Ajouter", id: "find_person_submit" %>

    <% end %>
  </div>
</div>

<div id="notifications">
  <div id="notif_wrapper">
    <div id="notif_wrapper_text">
      <h3>Invitation</h3>
      <p>Invite a friend ! My code: <%= "#{User.first.uuid}" %></p>

      <p>Pending request</p>
      <ul>
      <% current_user.pending_requests.each do |friendship| %>

        <li><%= friendship.friend.full_name %></li>

      <% end %>
      </ul>

      <p>Incoming request</p>
      <ul>
      <% current_user.incoming_requests.each do |friendship| %>

        <li>
          <%= friendship.user.full_name %> 
          <%= link_to "Accept", friendship_path(friendship), method: :patch %> 
          <%= link_to "Reject", friendship_path(friendship), method: :delete %></li>

      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div id="header">
  <div class="menu_element">
    <a href="#about">
      <p>About</p>
    </a>
  </div>
  <div class="menu_element">
    <a href="#how_to">
      <p>How does it work?</p>
    </a>
  </div>
  <div class="menu_element">
    <% if signed_in? %>
    <p>
      <p><%= link_to "Dashboard", dashboard_path %></p>
    </p>
    <% else %>
    <a href="#inscription">
      <p>Sign up / Sign in</p>
    </a>
    <%end%>
  </div>
</div>
<div id="home">
  <div class="bande_left"></div>
  <div class="bande_right"></div>
  <div id="logo_slogan">
    <div id="logo_img">
      <%= image_tag "Logo2.png", alt:"Dear Unknown", id:"big_logo"%>
    </div>
    <p>- Comme une lettre à la poste -</p>
  </div>
  <div id="home_bottom"></div>
</div>
<div id="how_to">
  <div class="bande_left"></div>
  <div class="bande_right"></div>
  <div id="how_to_block">
    <h1>HOW DOES IT WORK ?</h1>
    <svg id="mySVG1">
      <polyline points="
                60, 10
                10, 10
                10, 450
                700, 450
                700, 10
                450, 10
                " fill="none" stroke="#4b5e53" stroke-width="10" />
    </svg>
    <p>The concept is simple. You send and receive letters, just like in the old days.</br>
      Find your correspondent and never get bored again.</br>
    </p>
  </div>
</div>
<div id="inscription">
  <div id="sign_in_form">
    <div class="go_back_from_form">
      <p onclick="dismissSignIn();"class="subscribe_buttons">Back</p>
    </div>
    <h1>Let's Go!</h1>
    <div id="sign_in_form_fields">
        <%= form_with scope: :session, url: sessions_path, local: true, id: "sign_in_form_back" do |f| %> 
          <%= f.email_field :email , id:"email", placeholder:"email"%>
          <%= f.password_field :password, id:"password_sign_in", placeholder:"password" %>
          <%= f.submit "Log In", id:"submit_button_sign_in"%> 
        <% end %>
    </div>
  </div>
  <div id="sign_up_form">
    <div class="go_back_from_form">
      <p onclick="dismissSignUp();" class="subscribe_buttons">Back</p>
    </div>
    <h1>Get Started!</h1>
    <div id="sign_up_form_fields">
      <%= form_for @user, html: { id:"sign_up_form_back"} do |f| %>
        <%= f.text_field :firstname, id:"fname",  placeholder:"First name" %>
        <%= f.text_field :lastname, id:"lname", placeholder:"Last name"%>
        <%= f.email_field :email , id:"email2", placeholder:"Email"%>
        <%= f.password_field :password, id:"password_sign_in2", placeholder:"Password" %>
        <%= f.password_field :password_confirmation, id:"password_sign_in2", placeholder:"Password confirmation" %>
        <%= f.submit "Sign Up", id:"submit_button_sign_up"%>
      <% end %>
      
    </div>
  </div>
  <svg id="mySVG3">
    <path fill="none" stroke="#4b5e53" stroke-width="10" id="triangle" d="M10 300 L500 300 L500 10 L10 10 Z" />
  </svg>
  <script>
    // Get the id of the <path> element and the length of <path>
    var triangle = document.getElementById("triangle");
    var length = triangle.getTotalLength();

    // The start position of the drawing
    triangle.style.strokeDasharray = length;

    // Hide the triangle by offsetting dash. Remove this line to show the triangle before scroll draw
    triangle.style.strokeDashoffset = length;

    // Find scroll percentage on scroll (using cross-browser properties), and offset dash same amount as percentage scrolled
    window.addEventListener("scroll", myFunction);

    function myFunction() {
      var scrollpercent = (document.body.scrollTop + document.documentElement.scrollTop) / (document.documentElement.scrollHeight - document.documentElement.clientHeight);

      var draw = length * scrollpercent * 1.5;

      // Reverse the drawing (when scrolling upwards)
      triangle.style.strokeDashoffset = length - draw;
    }
  </script>
  <div id="pop_up_subscribe">
    <h1>WANT TO WRITE ?</h1>
    <div id="button_zone">
      <% if signed_in? %>
      <div class="subscribe_buttons" id="sign_in">
        <p><a href="/dashboard" style="color: white;";>Dashboard</a></p>
      </div>
      <% else %>
      <div class="subscribe_buttons" id="sign_in">
        <p onclick="sign_in_event();" id="sign_in_p">Sign In</p>
      </div>
      <div class="subscribe_buttons" id="sign_up">
        <p onclick="sign_up_event();" id="sign_up_p">Sign Up</p>
      </div>
      <% end %>
    </div>
    <script>
      function btn_set_zIndex(i){
        document.getElementById("sign_up_p").style.zIndex = i
        document.getElementById("sign_in_p").style.zIndex = i
      }
      function sign_in_event() {
        document.getElementById("sign_in_form").style.visibility = "visible";
        btn_set_zIndex(0);
      }
      
      function sign_up_event() {
        document.getElementById("sign_up_form").style.visibility = "visible";
        btn_set_zIndex(0);
      }

      function dismissSignIn() {
        document.getElementById("sign_in_form").style.visibility = "hidden";
        btn_set_zIndex(1);
      }

      function dismissSignUp() {
        document.getElementById("sign_up_form").style.visibility = "hidden";
        btn_set_zIndex(1);
      }
    </script>

  </div>
  <div id="lettre">
    <%= image_tag "lettre.png", alt:"lettre", id: "lettre_image" %>
  </div>

</div>
<div id="about">
  <div class="bande_left"></div>
  <div class="bande_right"></div>
  <div id="about_block">
    <h1>ABOUT</h1>
    <svg id="mySVG2">
      <polyline points="
                470, 10
                10, 10
                10, 450
                700, 450
                700, 10
                640, 10
                " fill="none" stroke="#ebc489" stroke-width="10" />
    </svg>
    <p>
      Rethink the concept of pen-friend in digital form.</br>
      We aim to reconnect people together and fight instant messaging to achieve authentic communication, therefore there is a minimum length required for every message ! 
    </p>
  </div>
  <div id="about_footer">
    Dear Unknown : Copyright @2020 
  </div>
</div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

  <%= f.label :firstname %>
  <%= f.text_field :firstname %>

  <%= f.label :lastname %>
  <%= f.text_field :lastname %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>

<% end %>